const prefix = 'todolist_';
export const TITLE_CHANGED = `${prefix}title_changed`;
export const DESCRIPTION_CHANGED = `${prefix}description_changed`;
export const ITEM_CREATED = `${prefix}item_created`;
export const VALID_TITLE_DESCRIPTION = `${prefix}valid_title_description`;
export const NOT_VALID_TITLE_DESCRIPTION = `${prefix}not_valid_title_description`;
export const GET_ITEMS = `${prefix}get_items`;
export const NO_CONNECTION = `${prefix}no_connection`;
export const FILTERING = `${prefix}filtering`;